# Generated by Django 2.0.5 on 2018-05-21 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadgerated',
            name='advisor',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='leadgerated',
            name='program',
            field=models.CharField(default='Teste', max_length=150),
            preserve_default=False,
        ),
    ]
