# Generated by Django 2.0.5 on 2018-05-21 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead_manager', '0002_auto_20180521_1331'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.AddField(
            model_name='leadgerated',
            name='subjects',
            field=models.ManyToManyField(null=True, to='lead_manager.Subject', verbose_name='list of subjects'),
        ),
    ]
